# speed duty cycle, range from -1 to 1
duty_cycle_min: -1.0
duty_cycle_max: 1.0

# current control in amps
current_min: 0.0
current_max: 20.0

# braking current in amps
brake_min: -20.0
brake_max: 20.0

# motor speed in rpm
# negative correspond to car moving forward
speed_min: -10000
speed_max: 5000

# servo duty cycle, range from 0.0 to 1.0
# limits correspond to the vehicle max and min steering angle
servo_min: 0.285
servo_max: 0.715
