#TrajectoryPlannerROS:
#  max_vel_x: 6.0
#  min_vel_x: 1.0
#  max_vel_theta: 1.0

#  acc_lim_theta: 3.2
#  acc_lim_x: 2.5
#  acc_lim_y: 2.5

#  holonomic_robot: false
#  meter_scoring: true

TebLocalPlannerROS:
  acc_lim_x: 2.0
  acc_lim_theta: 0.5
  
  max_vel_x: 6.0
  max_vel_x_backwards: 3.0
  max_vel_theta: 0.3
  
  min_turning_radius: 0.5
  wheelbase: 0.257
  cmd_angle_instead_rotvel: true
