obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.129, 0.082], [-0.128, 0.082], [-0.128, -0.082], [0.129, -0.082]]
inflation_radius: 0.2
transform_tolerance: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
